// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpo20fVUtybs0RW-nvlHPXbJYFaa60yc',
    appId: '1:6781619402:web:aa18782e2f82cdec283833',
    messagingSenderId: '6781619402',
    projectId: 'avotek-4e8e3',
    authDomain: 'avotek-4e8e3.firebaseapp.com',
    storageBucket: 'avotek-4e8e3.firebasestorage.app',
    measurementId: 'G-1V0M21YV0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSaEsjAMpuVLN5E0wWXuP1XtXPnNEoyE',
    appId: '1:6781619402:android:ac021b6499966eb5283833',
    messagingSenderId: '6781619402',
    projectId: 'avotek-4e8e3',
    storageBucket: 'avotek-4e8e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1g06E2Y3bFTHAq6_MwnP9Ivf4h4MYyGw',
    appId: '1:6781619402:ios:90857c6829106639283833',
    messagingSenderId: '6781619402',
    projectId: 'avotek-4e8e3',
    storageBucket: 'avotek-4e8e3.firebasestorage.app',
    iosClientId: '6781619402-mmdgbgoj8ma1rjrd0et68k995kf2ilqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1g06E2Y3bFTHAq6_MwnP9Ivf4h4MYyGw',
    appId: '1:6781619402:ios:90857c6829106639283833',
    messagingSenderId: '6781619402',
    projectId: 'avotek-4e8e3',
    storageBucket: 'avotek-4e8e3.firebasestorage.app',
    iosClientId: '6781619402-mmdgbgoj8ma1rjrd0et68k995kf2ilqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUpo20fVUtybs0RW-nvlHPXbJYFaa60yc',
    appId: '1:6781619402:web:8d9a14b87e4143d4283833',
    messagingSenderId: '6781619402',
    projectId: 'avotek-4e8e3',
    authDomain: 'avotek-4e8e3.firebaseapp.com',
    storageBucket: 'avotek-4e8e3.firebasestorage.app',
    measurementId: 'G-P3CE89LFLR',
  );
}
